<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ángela Reverte Pagola">

<title>Trabajo 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Trabajo2_Reverte_Pagola_Angela_files/libs/clipboard/clipboard.min.js"></script>
<script src="Trabajo2_Reverte_Pagola_Angela_files/libs/quarto-html/quarto.js"></script>
<script src="Trabajo2_Reverte_Pagola_Angela_files/libs/quarto-html/popper.min.js"></script>
<script src="Trabajo2_Reverte_Pagola_Angela_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Trabajo2_Reverte_Pagola_Angela_files/libs/quarto-html/anchor.min.js"></script>
<link href="Trabajo2_Reverte_Pagola_Angela_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Trabajo2_Reverte_Pagola_Angela_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Trabajo2_Reverte_Pagola_Angela_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Trabajo2_Reverte_Pagola_Angela_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Trabajo2_Reverte_Pagola_Angela_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="Trabajo2_Reverte_Pagola_Angela_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

<script src="Trabajo2_Reverte_Pagola_Angela_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<script src="Trabajo2_Reverte_Pagola_Angela_files/libs/viz-1.8.2/viz.js"></script>

<link href="Trabajo2_Reverte_Pagola_Angela_files/libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">

<script src="Trabajo2_Reverte_Pagola_Angela_files/libs/grViz-binding-1.0.11/grViz.js"></script>

<script src="Trabajo2_Reverte_Pagola_Angela_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="Trabajo2_Reverte_Pagola_Angela_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#presentación-del-problema." id="toc-presentación-del-problema." class="nav-link active" data-scroll-target="#presentación-del-problema."><span class="header-section-number">1</span> PRESENTACIÓN DEL PROBLEMA.</a></li>
  <li><a href="#solución-problema." id="toc-solución-problema." class="nav-link" data-scroll-target="#solución-problema."><span class="header-section-number">2</span> SOLUCIÓN PROBLEMA.</a>
  <ul class="collapse">
  <li><a href="#resolución-con-ahp-con-r." id="toc-resolución-con-ahp-con-r." class="nav-link" data-scroll-target="#resolución-con-ahp-con-r."><span class="header-section-number">2.1</span> Resolución con AHP con R.</a></li>
  <li><a href="#resolución-con-ahp-con-librería-ahp." id="toc-resolución-con-ahp-con-librería-ahp." class="nav-link" data-scroll-target="#resolución-con-ahp-con-librería-ahp."><span class="header-section-number">2.2</span> Resolución con AHP con librería AHP.</a></li>
  <li><a href="#resolución-con-electre." id="toc-resolución-con-electre." class="nav-link" data-scroll-target="#resolución-con-electre."><span class="header-section-number">2.3</span> Resolución con Electre.</a>
  <ul class="collapse">
  <li><a href="#electre-completo-con-tablas." id="toc-electre-completo-con-tablas." class="nav-link" data-scroll-target="#electre-completo-con-tablas."><span class="header-section-number">2.3.1</span> Electre completo con tablas.</a></li>
  </ul></li>
  <li><a href="#resolución-con-promethee-con-r." id="toc-resolución-con-promethee-con-r." class="nav-link" data-scroll-target="#resolución-con-promethee-con-r."><span class="header-section-number">2.4</span> Resolución con Promethee con R.</a>
  <ul class="collapse">
  <li><a href="#promethee-i" id="toc-promethee-i" class="nav-link" data-scroll-target="#promethee-i"><span class="header-section-number">2.4.1</span> Promethee I</a></li>
  <li><a href="#promethee-ii" id="toc-promethee-ii" class="nav-link" data-scroll-target="#promethee-ii"><span class="header-section-number">2.4.2</span> Promethee II</a></li>
  </ul></li>
  <li><a href="#promethee-windows." id="toc-promethee-windows." class="nav-link" data-scroll-target="#promethee-windows."><span class="header-section-number">2.5</span> Promethee Windows.</a></li>
  <li><a href="#método-axiomático-de-arrow-y-raymond" id="toc-método-axiomático-de-arrow-y-raymond" class="nav-link" data-scroll-target="#método-axiomático-de-arrow-y-raymond"><span class="header-section-number">2.6</span> Método Axiomático de Arrow y Raymond</a>
  <ul class="collapse">
  <li><a href="#análisis-paramétrico-o-de-sensibilidad-aplicación-método-axiomático-de-arrow-y-raymond" id="toc-análisis-paramétrico-o-de-sensibilidad-aplicación-método-axiomático-de-arrow-y-raymond" class="nav-link" data-scroll-target="#análisis-paramétrico-o-de-sensibilidad-aplicación-método-axiomático-de-arrow-y-raymond"><span class="header-section-number">2.6.1</span> Análisis paramétrico o de sensibilidad aplicación Método axiomático de Arrow y Raymond</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusión." id="toc-conclusión." class="nav-link" data-scroll-target="#conclusión."><span class="header-section-number">3</span> CONCLUSIÓN.</a></li>
  <li><a href="#bibliografía." id="toc-bibliografía." class="nav-link" data-scroll-target="#bibliografía."><span class="header-section-number">4</span> BIBLIOGRAFÍA.</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo 2</h1>
<p class="subtitle lead">Elección club deportivo para practicar tenis</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ángela Reverte Pagola </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="presentación-del-problema." class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> PRESENTACIÓN DEL PROBLEMA.</h1>
<p>Mi pasión siempre han sido los deportes. He practicado muchos como: natación, baloncesto, tenis o fútbol sala. Este año, quiero volver a jugar al tenis y me encuentro emocionada. El problema es que tengo muchas opciones de clubes de tenis donde apuntarme y no sé qué hacer.</p>
<p>Para mí, el deporte es algo esencial en mi vida y, aunque no me quiero dedicar de forma profesional, me gusta mucho que los entrenamientos sean muy intensos y lo más profesionales posibles. Sin embargo, creo que el ambiente debe ser divertido y relajado. Tan importante es hacer deporte serio como disfrutarlo y pasarlo bien.</p>
<p>Por otro lado, durante el día estoy muy ajetreada, por lo que es importante no perder tiempo en el desplazamiento. Lo ideal sería que el club estuviera cerca de casa o, por lo menos, que tuviera fácil aparcamiento.</p>
<p>En cuanto a lo económico, para mí no es tan importante. Los precios son todos parecidos, aunque sí es verdad que algunos incluyen más servicios que otros. De hecho, es importante destacar que no todos los clubes tienen las mismas instalaciones. A mi me encanta alquilar pistas con mi hermano y amigos para jugar. Y no todos los clubes tienen las mismas facilidades.</p>
<p>Veamos ahora las diferentes alternativas y una breve presentación de ellas:</p>
<ul>
<li><p>Club Mirador: Club muy cercano a mi casa (5 mins andando). Es un club social y pequeño, pero muy familiar. Cuenta con una escuela de tenis que lleva este deporte también en otros clubes. Todos los monitores son profesionales y muy cercanos. El problema es que cuenta solo con una pista de tenis, por lo que, por un lado, las clases de tenis tienen un alto número de alumnos y, por otro, es difícil reservarla, pues siempre está ocupada. Esta escuela de tenis se preocupa mucho por hacer eventos y torneos. Siempre con el objetivo de pasarlo bien. Es perfecta para tener el tenis como ocio. Es bastante económica.</p></li>
<li><p>Club Bernier: aunque también es un club social, su objetivo principal es el tenis. Bastante profesional, pero sin perder de vista el ocio y el disfrute. Está también muy cerca de casa (10 mins andando). Cuenta con 4 pistas de tenis, gimnasio, pistas de padel y bar/restaurante. También realizan muchos partidos y torneos en los que te puedes poner a prueba como tenista. No es tan económico.</p></li>
<li><p>Club de tenis Río Grande: club dedicado al tenis. Este club se dedica al tenis, aunque cuenta también con otros muchos servicios como piscina, sala fitness, pistas de padel o campos de fútbol. Es un club muy grande, con 16 pistas de tenis, de las cuales 12 son de tierra batida y en muy buen estado. Hay grupos de entrenamientos en función de tus objetivos: ocio, entrenamiento intenso, mejorar la técnica… Se encuentra a 5 mins en coche de mi casa y tiene parking. Hay buen ambiente, pero al ser tan grande, se pierde un poco la familiaridad. Es más caro.</p></li>
<li><p>Real Club de Tenis Betis: club histórico de tenis en Sevilla. Reconocido a nivel nacional. Ideal si quieres mejorar y entrenar de forma intensa. Realiza grandes torneos y está hermanado con otros clubes de tenis de España. Cuenta con 6 pistas de tenis de tierra batida, gimansio, pistas de padel y piscina. Se sitúa en Sevilla, por lo que está a 15 minutos en coche, más el tiempo de aparcamiento. Es caro.</p></li>
</ul>
<div style="page-break-after: always;"></div>
</section>
<section id="solución-problema." class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> SOLUCIÓN PROBLEMA.</h1>
<p>En primer lugar, vamos a presentar los criterios y subcriterios tenidos en cuenta:</p>
<ul>
<li><p>Ambiente: la buena relación entre alumnos y monitores es esencial. Este criterio, los vamos a dividir en dos subcriterios: familiaridad y eventos deportivos. Familiaridad: se agradece el buen rollo y las ganas de disfrutar el deporte. Tanto entre los alumnos como con los monitores. Eventos deportivos: súper importante para crear vínculos con otros jugadores y para crear un ambiente deportivo y de competición.</p></li>
<li><p>Servicios: este criterio también lo vamos a dividir en dos subcriterios: pistas de tenis e instalaciones. En primer lugar, pistas de tenis: lo ideal es que haya varias pistas de tenis, para poder alquilarlas y que estén en buen estado. Instalaciones: siempre es mejor que el club posea otras istalaciones como gimnasio, pistas de padel o bar, para que se convierta en un club donde disfrutar, además de hacer deporte.</p></li>
<li><p>Ubicación y accesibilidad: debido a la falta de tiempo, lo ideal es que el club esté cerca de casa o, por lo menos, que sea fácil de aparcar con el coche.</p></li>
<li><p>Precio: debido a que no quiero dedicarme profesionalmente, los precios deben ser asequibles.</p></li>
<li><p>Entrenamientos: aunque mi principal objetivo sea divertirme mientras hago deporte, para mí es esencial que los entrenamientos sean intensos y competitivos.</p></li>
</ul>
<p>Una vez presentados el problema, los criterios y las alternativas, procedemos a aplicar las diferentes técnicas de decisión multicriterio.</p>
<div style="page-break-after: always;"></div>
<section id="resolución-con-ahp-con-r." class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="resolución-con-ahp-con-r."><span class="header-section-number">2.1</span> Resolución con AHP con R.</h2>
<p>Con toda la información anterior, voy a contruir las tablas de comparación 2 a 2. Y calculamos los pesos locales:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"teoriadecision_funciones_multicriterio.R"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"teoriadecision_funciones_multicriterio_diagram.R"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: shape</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"teoriadecision_funciones_multicriterio_utiles.R"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>n.criterios <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Ambiente"</span>,<span class="st">"Servicios"</span>,<span class="st">"Ubicación y accesibilidad"</span>,<span class="st">"Precio"</span>,<span class="st">"Entrenamientos"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>tab1 <span class="ot">=</span> <span class="fu">multicriterio.crea.matrizvaloraciones_mej</span>(<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">7</span>),<span class="dv">5</span>,n.criterios)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>tab1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                           Ambiente Servicios Ubicación y accesibilidad Precio
Ambiente                  1.0000000 2.0000000                 0.3333333      5
Servicios                 0.5000000 1.0000000                 0.2500000      3
Ubicación y accesibilidad 3.0000000 4.0000000                 1.0000000      6
Precio                    0.2000000 0.3333333                 0.1666667      1
Entrenamientos            0.3333333 2.0000000                 0.5000000      7
                          Entrenamientos
Ambiente                       3.0000000
Servicios                      0.5000000
Ubicación y accesibilidad      2.0000000
Precio                         0.1428571
Entrenamientos                 1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>pl1 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.variante1.autovectormayorautovalor</span>(tab1)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">pl1r =</span> <span class="fu">round</span>(pl1<span class="sc">$</span>valoraciones.ahp,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Ambiente                 Servicios Ubicación y accesibilidad 
                   0.2554                    0.1037                    0.4157 
                   Precio            Entrenamientos 
                   0.0419                    0.1833 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ambiente:</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>n.criterios2 <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Familiaridad"</span>,<span class="st">"Eventos deportivos"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>tab2 <span class="ot">=</span> <span class="fu">multicriterio.crea.matrizvaloraciones_mej</span>(<span class="fu">c</span>(<span class="dv">2</span>),<span class="dv">2</span>,n.criterios2)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>tab2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Familiaridad Eventos deportivos
Familiaridad                1.0                  2
Eventos deportivos          0.5                  1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>pl2 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.variante1.autovectormayorautovalor</span>(tab2)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">pl2r =</span> <span class="fu">round</span>(pl2<span class="sc">$</span>valoraciones.ahp,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Familiaridad Eventos deportivos 
            0.6667             0.3333 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Servicios</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>n.criterios3 <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Pistas de tenis"</span>,<span class="st">"Instalaciones"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>tab3 <span class="ot">=</span> <span class="fu">multicriterio.crea.matrizvaloraciones_mej</span>(<span class="fu">c</span>(<span class="dv">6</span>),<span class="dv">2</span>,n.criterios3)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>tab3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Pistas de tenis Instalaciones
Pistas de tenis       1.0000000             6
Instalaciones         0.1666667             1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>pl3 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.variante1.autovectormayorautovalor</span>(tab3)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">pl3r =</span> <span class="fu">round</span>(pl3<span class="sc">$</span>valoraciones.ahp,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pistas de tenis   Instalaciones 
         0.8571          0.1429 </code></pre>
</div>
</div>
<p>De esta forma, ya tenemos todos los pesos locales de todos los criterios y subcriterios:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>C11 <span class="ot">=</span> <span class="fl">0.2554</span> <span class="sc">*</span> <span class="fl">0.6667</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>C12 <span class="ot">=</span> <span class="fl">0.2554</span> <span class="sc">*</span> <span class="fl">0.3333</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>C21 <span class="ot">=</span> <span class="fl">0.1037</span> <span class="sc">*</span> <span class="fl">0.8571</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>C22 <span class="ot">=</span> <span class="fl">0.1037</span> <span class="sc">*</span> <span class="fl">0.1429</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>C3 <span class="ot">=</span> <span class="fl">0.4157</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>C4 <span class="ot">=</span> <span class="fl">0.0419</span> </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>C5 <span class="ot">=</span> <span class="fl">0.1833</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>crisub <span class="ot">=</span> <span class="fu">c</span>(C11,C12,C21,C22,C3,C4,C5)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>crisub</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.17027518 0.08512482 0.08888127 0.01481873 0.41570000 0.04190000 0.18330000</code></pre>
</div>
</div>
<p>Del mismo modo, calculamos los pesos locales para las alternativas en función de cada criterio y subcriterio:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Familiaridad</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>n.alternativas <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Mirador"</span>,<span class="st">"Bernier"</span>,<span class="st">"Río Grande"</span>,<span class="st">"Tenis Betis"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>tab4 <span class="ot">=</span> <span class="fu">multicriterio.crea.matrizvaloraciones_mej</span>(<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">2</span>),<span class="dv">4</span>,n.alternativas)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>tab4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Mirador Bernier Río Grande Tenis Betis
Mirador     1.0000000    2.00        4.0           6
Bernier     0.5000000    1.00        2.0           4
Río Grande  0.2500000    0.50        1.0           2
Tenis Betis 0.1666667    0.25        0.5           1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>pl4 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.variante1.autovectormayorautovalor</span>(tab4)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">pl4r =</span> <span class="fu">round</span>(pl4<span class="sc">$</span>valoraciones.ahp,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Mirador     Bernier  Río Grande Tenis Betis 
     0.5132      0.2751      0.1376      0.0741 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Eventos deportivos</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>tab5 <span class="ot">=</span> <span class="fu">multicriterio.crea.matrizvaloraciones_mej</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>),<span class="dv">4</span>,n.alternativas)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>tab5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Mirador   Bernier Río Grande Tenis Betis
Mirador           1 0.3333333  0.2000000   0.1666667
Bernier           3 1.0000000  0.3333333   0.2000000
Río Grande        5 3.0000000  1.0000000   0.3333333
Tenis Betis       6 5.0000000  3.0000000   1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>pl5 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.variante1.autovectormayorautovalor</span>(tab5)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">pl5r =</span> <span class="fu">round</span>(pl5<span class="sc">$</span>valoraciones.ahp,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Mirador     Bernier  Río Grande Tenis Betis 
     0.0589      0.1195      0.2661      0.5554 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Pistas de tenis</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>tab6 <span class="ot">=</span> <span class="fu">multicriterio.crea.matrizvaloraciones_mej</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">9</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">7</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">6</span>),<span class="dv">4</span>,n.alternativas)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>tab6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Mirador   Bernier Río Grande Tenis Betis
Mirador           1 0.3333333  0.1111111   0.1666667
Bernier           3 1.0000000  0.1428571   0.5000000
Río Grande        9 7.0000000  1.0000000   6.0000000
Tenis Betis       6 2.0000000  0.1666667   1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>pl6 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.variante1.autovectormayorautovalor</span>(tab6)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">pl6r =</span> <span class="fu">round</span>(pl6<span class="sc">$</span>valoraciones.ahp,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Mirador     Bernier  Río Grande Tenis Betis 
     0.0434      0.0993      0.6780      0.1794 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Instalaciones</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>tab7 <span class="ot">=</span> <span class="fu">multicriterio.crea.matrizvaloraciones_mej</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">4</span>),<span class="dv">4</span>,n.alternativas)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>tab7</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Mirador Bernier Río Grande Tenis Betis
Mirador         1.0     0.5  0.2000000           2
Bernier         2.0     1.0  0.3333333           2
Río Grande      5.0     3.0  1.0000000           4
Tenis Betis     0.5     0.5  0.2500000           1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>pl7 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.variante1.autovectormayorautovalor</span>(tab7)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">pl7r =</span> <span class="fu">round</span>(pl7<span class="sc">$</span>valoraciones.ahp,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Mirador     Bernier  Río Grande Tenis Betis 
     0.1349      0.2116      0.5529      0.1006 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ubicación</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>tab8 <span class="ot">=</span> <span class="fu">multicriterio.crea.matrizvaloraciones_mej</span>(<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">9</span>,<span class="dv">3</span>,<span class="dv">8</span>,<span class="dv">7</span>),<span class="dv">4</span>,n.alternativas)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>tab8</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Mirador   Bernier Río Grande Tenis Betis
Mirador     1.0000000 2.0000000  5.0000000           9
Bernier     0.5000000 1.0000000  3.0000000           8
Río Grande  0.2000000 0.3333333  1.0000000           7
Tenis Betis 0.1111111 0.1250000  0.1428571           1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>pl8 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.variante1.autovectormayorautovalor</span>(tab8)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">pl8r =</span> <span class="fu">round</span>(pl8<span class="sc">$</span>valoraciones.ahp,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Mirador     Bernier  Río Grande Tenis Betis 
     0.5157      0.3050      0.1431      0.0362 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Precio</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>tab9 <span class="ot">=</span> <span class="fu">multicriterio.crea.matrizvaloraciones_mej</span>(<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">2</span>),<span class="dv">4</span>,n.alternativas)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>tab9</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Mirador Bernier Río Grande Tenis Betis
Mirador     1.0000000    3.00        5.0           6
Bernier     0.3333333    1.00        2.0           4
Río Grande  0.2000000    0.50        1.0           2
Tenis Betis 0.1666667    0.25        0.5           1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>pl9 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.variante1.autovectormayorautovalor</span>(tab9)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">pl9r =</span> <span class="fu">round</span>(pl9<span class="sc">$</span>valoraciones.ahp,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Mirador     Bernier  Río Grande Tenis Betis 
     0.5715      0.2355      0.1224      0.0706 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Entrenamientos</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>tab10 <span class="ot">=</span> <span class="fu">multicriterio.crea.matrizvaloraciones_mej</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">8</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>),<span class="dv">4</span>,n.alternativas)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>tab10</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Mirador Bernier Río Grande Tenis Betis
Mirador           1    0.25  0.2000000   0.1250000
Bernier           4    1.00  0.3333333   0.1666667
Río Grande        5    3.00  1.0000000   0.3333333
Tenis Betis       8    6.00  3.0000000   1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>pl10 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.variante1.autovectormayorautovalor</span>(tab10)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">pl10r =</span> <span class="fu">round</span>(pl10<span class="sc">$</span>valoraciones.ahp,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Mirador     Bernier  Río Grande Tenis Betis 
     0.0482      0.1182      0.2500      0.5836 </code></pre>
</div>
</div>
<p>Una vez calculados los pesos locales, pasamos a los pesos globales. Al ser un problema multinivel, los vamos a calcular a mano. Aunque podamos sacar todas las conclusiones con estos resultados, voy a terminar de explicarlas con la librería AHP, pues todas las tablas se aprecian mucho mejor y tenemos las mismas soluciones pero de forma más visual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>matper <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.5132</span>,<span class="fl">0.2751</span>,<span class="fl">0.1376</span>,<span class="fl">0.0741</span>,</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>                  <span class="fl">0.0589</span>,<span class="fl">0.1195</span>,<span class="fl">0.2661</span>,<span class="fl">0.5554</span>,</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                  <span class="fl">0.0434</span>,<span class="fl">0.0993</span>,<span class="fl">0.6780</span>,<span class="fl">0.1794</span>,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                  <span class="fl">0.1349</span>,<span class="fl">0.2116</span>,<span class="fl">0.5529</span>,<span class="fl">0.1006</span>,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>                  <span class="fl">0.5157</span>,<span class="fl">0.3050</span>,<span class="fl">0.1431</span>,<span class="fl">0.0362</span>,</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>                  <span class="fl">0.5715</span>,<span class="fl">0.2355</span>,<span class="fl">0.1224</span>,<span class="fl">0.0706</span>,</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>                  <span class="fl">0.0482</span>,<span class="fl">0.1182</span>,<span class="fl">0.2500</span>,<span class="fl">0.5836</span>),<span class="at">ncol=</span><span class="dv">4</span>,<span class="at">nrow=</span><span class="dv">7</span>,<span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>pond.globales <span class="ot">=</span> crisub <span class="sc">%*%</span> matper</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(pond.globales) <span class="ot">=</span> n.alternativas</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>pond.globales</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Mirador   Bernier Río Grande Tenis Betis
[1,] 0.345413 0.2272987  0.2249766   0.2023121</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(pond.globales<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Mirador Bernier Río Grande Tenis Betis
[1,]   34.54   22.73       22.5       20.23</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>Mcrisub <span class="ot">=</span> <span class="fu">matrix</span>(crisub,<span class="at">ncol=</span><span class="dv">4</span>,<span class="at">nrow=</span><span class="dv">7</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>Mcrisub</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           [,1]       [,2]       [,3]       [,4]
[1,] 0.17027518 0.17027518 0.17027518 0.17027518
[2,] 0.08512482 0.08512482 0.08512482 0.08512482
[3,] 0.08888127 0.08888127 0.08888127 0.08888127
[4,] 0.01481873 0.01481873 0.01481873 0.01481873
[5,] 0.41570000 0.41570000 0.41570000 0.41570000
[6,] 0.04190000 0.04190000 0.04190000 0.04190000
[7,] 0.18330000 0.18330000 0.18330000 0.18330000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>pond.globales.parciales <span class="ot">=</span> Mcrisub<span class="sc">*</span>matper</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(pond.globales.parciales<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]  [,2] [,3]  [,4]
[1,]  8.74  4.68 2.34  1.26
[2,]  0.50  1.02 2.27  4.73
[3,]  0.39  0.88 6.03  1.59
[4,]  0.20  0.31 0.82  0.15
[5,] 21.44 12.68 5.95  1.50
[6,]  2.39  0.99 0.51  0.30
[7,]  0.88  2.17 4.58 10.70</code></pre>
</div>
</div>
<p>CONCLUSIONES: Viendo los resultados, elegiríamos el club Mirador, con un 34,54%, seguido del club Bernier con un 22.73%. Las interpretaciones de por qué han salido estos resultados, la vamos a ver mejor con la librería AHP como he comentado anteriormente.</p>
<p>Veamos ahora la inconsistencia de cada una de las tablas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>Inconsistencia1 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.coef.inconsistencia</span>(tab1)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(Inconsistencia1<span class="sc">$</span>mensaje, <span class="fu">round</span>(Inconsistencia1<span class="sc">$</span>RI.coef.inconsistencia,<span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Consistencia aceptable" "0.0731"                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>Inconsistencia2 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.coef.inconsistencia</span>(tab2)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(Inconsistencia2<span class="sc">$</span>mensaje, <span class="fu">round</span>(Inconsistencia2<span class="sc">$</span>RI.coef.inconsistencia,<span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Consistencia aceptable" "NaN"                   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>Inconsistencia3 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.coef.inconsistencia</span>(tab3)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(Inconsistencia3<span class="sc">$</span>mensaje, <span class="fu">round</span>(Inconsistencia3<span class="sc">$</span>RI.coef.inconsistencia,<span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Consistencia aceptable" "NaN"                   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>Inconsistencia4 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.coef.inconsistencia</span>(tab4)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(Inconsistencia4<span class="sc">$</span>mensaje, <span class="fu">round</span>(Inconsistencia4<span class="sc">$</span>RI.coef.inconsistencia,<span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Consistencia aceptable" "0.0038"                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>Inconsistencia5 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.coef.inconsistencia</span>(tab5)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(Inconsistencia5<span class="sc">$</span>mensaje, <span class="fu">round</span>(Inconsistencia5<span class="sc">$</span>RI.coef.inconsistencia,<span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Consistencia aceptable" "0.0557"                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>Inconsistencia6 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.coef.inconsistencia</span>(tab6)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(Inconsistencia6<span class="sc">$</span>mensaje, <span class="fu">round</span>(Inconsistencia6<span class="sc">$</span>RI.coef.inconsistencia,<span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Consistencia aceptable" "0.0699"                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>Inconsistencia7 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.coef.inconsistencia</span>(tab7)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(Inconsistencia7<span class="sc">$</span>mensaje, <span class="fu">round</span>(Inconsistencia7<span class="sc">$</span>RI.coef.inconsistencia,<span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Consistencia aceptable" "0.0356"                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>Inconsistencia8 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.coef.inconsistencia</span>(tab8)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(Inconsistencia8<span class="sc">$</span>mensaje, <span class="fu">round</span>(Inconsistencia8<span class="sc">$</span>RI.coef.inconsistencia,<span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Consistencia aceptable" "0.0747"                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>Inconsistencia9 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.coef.inconsistencia</span>(tab9)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(Inconsistencia9<span class="sc">$</span>mensaje, <span class="fu">round</span>(Inconsistencia9<span class="sc">$</span>RI.coef.inconsistencia,<span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Consistencia aceptable" "0.0181"                </code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>Inconsistencia10 <span class="ot">=</span> <span class="fu">multicriterio.metodoAHP.coef.inconsistencia</span>(tab10)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(Inconsistencia10<span class="sc">$</span>mensaje, <span class="fu">round</span>(Inconsistencia10<span class="sc">$</span>RI.coef.inconsistencia,<span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Consistencia aceptable" "0.0597"                </code></pre>
</div>
</div>
<p>Podemos comprobar que todas las matrices tienen consistencia aceptable. Por lo que las valoraciones que hemos puesto tienen sentido. No hay errores de inconsistencia y en las tablas no se forman ciclos entre preferencias de las alternativas y criterios.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="resolución-con-ahp-con-librería-ahp." class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="resolución-con-ahp-con-librería-ahp."><span class="header-section-number">2.2</span> Resolución con AHP con librería AHP.</h2>
<p>Ahora vamos a hacer lo mismo, pero con la ayuda de la librería AHP. Para ello, he plasmado toda la información en el fichero esquema.ahp. Deben salir las mismas conclusiones, pero vamos a comentarlas en esta sección, pues la salida es mucho más visual e intuitiva.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ahp)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">=</span> <span class="fu">Load</span>(<span class="st">"esquema.ahp"</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Calculate</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Visualize</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-99c17f1d9bea8e69b525" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-99c17f1d9bea8e69b525">{"x":{"diagram":"digraph {\n\ngraph [rankdir = \"TB\"]\n\n\n\n  \"1\" [label = \"Elegir el club donde practicar tenis\", tooltip = \"\", style = \"filled,rounded\", shape = \"box\", color = \"honeydew4\", fillcolor = \"#F0FFF0\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"black\"] \n  \"2\" [label = \"Ambiente\", tooltip = \"priority: 25.5%\n\", style = \"filled,rounded\", shape = \"box\", color = \"honeydew4\", fillcolor = \"#F0FFF0\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"black\"] \n  \"3\" [label = \"Familiaridad\", tooltip = \"priority: 66.7%\n\", style = \"filled,rounded\", shape = \"box\", color = \"honeydew4\", fillcolor = \"#F0FFF0\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"black\"] \n  \"4\" [label = \"Eventos deportivos\", tooltip = \"priority: 33.3%\n\", style = \"filled,rounded\", shape = \"box\", color = \"honeydew4\", fillcolor = \"#F0FFF0\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"black\"] \n  \"5\" [label = \"Servicios\", tooltip = \"priority: 10.4%\n\", style = \"filled,rounded\", shape = \"box\", color = \"honeydew4\", fillcolor = \"#F0FFF0\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"black\"] \n  \"6\" [label = \"Pistas de tenis\", tooltip = \"priority: 85.7%\n\", style = \"filled,rounded\", shape = \"box\", color = \"honeydew4\", fillcolor = \"#F0FFF0\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"black\"] \n  \"7\" [label = \"Instalaciones\", tooltip = \"priority: 14.3%\n\", style = \"filled,rounded\", shape = \"box\", color = \"honeydew4\", fillcolor = \"#F0FFF0\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"black\"] \n  \"8\" [label = \"Ubicación y accesibilidad\", tooltip = \"priority: 41.6%\n\", style = \"filled,rounded\", shape = \"box\", color = \"honeydew4\", fillcolor = \"#F0FFF0\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"black\"] \n  \"9\" [label = \"Precio\", tooltip = \"priority: 4.2%\n\", style = \"filled,rounded\", shape = \"box\", color = \"honeydew4\", fillcolor = \"#F0FFF0\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"black\"] \n  \"10\" [label = \"Entrenamientos\", tooltip = \"priority: 18.3%\n\", style = \"filled,rounded\", shape = \"box\", color = \"honeydew4\", fillcolor = \"#F0FFF0\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"black\"] \n  \"11\" [label = \"Alternatives\", tooltip = \"\", style = \"filled,rounded\", shape = \"box\", color = \"thistle4\", fillcolor = \"#D8BFD8\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"\"] \n  \"12\" [label = \"Club Mirador\", tooltip = \"priority: 51.3%\n\", style = \"filled,rounded\", shape = \"box\", color = \"thistle4\", fillcolor = \"#D8BFD8\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"\"] \n  \"13\" [label = \"Club Bernier\", tooltip = \"priority: 27.5%\n\", style = \"filled,rounded\", shape = \"box\", color = \"thistle4\", fillcolor = \"#D8BFD8\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"\"] \n  \"14\" [label = \"Club Río Grande\", tooltip = \"priority: 13.8%\n\", style = \"filled,rounded\", shape = \"box\", color = \"thistle4\", fillcolor = \"#D8BFD8\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"\"] \n  \"15\" [label = \"Club Tenis Betis\", tooltip = \"priority: 7.4%\n\", style = \"filled,rounded\", shape = \"box\", color = \"thistle4\", fillcolor = \"#D8BFD8\", penwidth = \"4\", fontname = \"helvetica\", fontcolor = \"\"] \n\"1\"->\"2\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"1\"->\"5\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"1\"->\"8\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"1\"->\"9\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"1\"->\"10\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"2\"->\"3\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"2\"->\"4\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"5\"->\"6\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"5\"->\"7\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"3\"->\"11\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"4\"->\"11\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"6\"->\"11\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"7\"->\"11\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"8\"->\"11\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"9\"->\"11\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"10\"->\"11\" [arrowhead = \"vee\", color = \"grey35\", penwidth = \"2\", penwidth = \"2\"] \n\"11\"->\"12\" [penwidth = \"2\", color = \"grey35\", penwidth = \"2\", dir = \"none\"] \n\"11\"->\"13\" [dir = \"none\", color = \"grey35\", penwidth = \"2\", dir = \"none\"] \n\"11\"->\"14\" [dir = \"none\", color = \"grey35\", penwidth = \"2\", dir = \"none\"] \n\"11\"->\"15\" [dir = \"none\", color = \"grey35\", penwidth = \"2\", dir = \"none\"] \n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#pesos globales:</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">=</span> <span class="fu">AnalyzeTable</span>(datos)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">export_formattable</span>(<span class="fu">AnalyzeTable</span>(datos), <span class="at">file =</span> <span class="st">"tablaahpGlobal.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo2_Reverte_Pagola_Angela_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co">#pesos locales:</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>t2 <span class="ot">=</span> <span class="fu">AnalyzeTable</span>(datos, <span class="at">variable =</span> <span class="st">"priority"</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">export_formattable</span>(t2, <span class="at">file =</span> <span class="st">"tablaahpLocal.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo2_Reverte_Pagola_Angela_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#formattable::as.htmlwidget(t1)</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="co">#formattable::as.htmlwidget(t2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>CONCLUSIONES:</p>
<p>Viendo las tablas podemos sacar muchas conclusiones, por ejemplo:</p>
<ul>
<li><p>Elegimos la opción club Mirador, pues es el que tiene mejor puntuación: 34.5%.</p></li>
<li><p>Lo que más le puntúa para ser elegido es la ubicación y accesibilidad. Se le ha dado mucha importancia a que el club de tenis esté cerca de casa y, el club Mirador es el mejor en este aspecto. Además, al ser un club pequeño, hay mucha familiaridad y un muy buen ambiente, por lo que esto le suma mucho también. Teniendo en cuenta que son los dos criterios con más peso, esta alternativa sale ganadora.</p></li>
<li><p>Del mismo modo se puede pensar con el club Bernier. Se caracteriza por la ubicación y el ambiente. Aún así, al tener peores valoraciones que el club Mirador, se queda en segunda posición.</p></li>
<li><p>Por otro lado, el club Río Grande. El mejor en cuanto a los servicios debido al gran número de pistas de tenis que posee. Sin embargo, este no es el criterio con más peso y en los demás no es el mejor. Por eso termina en tercera posición.</p></li>
<li><p>Por último, el club Tenis Betis. La ubicación y accesibilidad es lo que más le penaliza, pues tiene muy mala valoración y es el criterio con más peso. Es el mejor en los entrenamientos, pues es un club bastante serio, pero no es suficiente para ser elegido.</p></li>
<li><p>La diferencia de pesos en los criterios hace realmente que nos decantemos por una u otra alternativa.</p></li>
<li><p>Se puede comprobar que todas las comparaciones tienen una inconsistencia de menos de un 10%, por lo que hemos valorado con buen criterio y sin muchas inconsistencias.</p></li>
</ul>
<div style="page-break-after: always;"></div>
</section>
<section id="resolución-con-electre." class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="resolución-con-electre."><span class="header-section-number">2.3</span> Resolución con Electre.</h2>
<p>En primer lugar creamos la matriz de decisión. Para ello, vamos a tratar los subcriterios como criterios y de esta forma veremos más fácil como aplicar este método. Vamos a darle estos valores a cada alternativa en cada criterio:</p>
<ul>
<li>Familiaridad: como es algo subjetivo, voy a poner un porcentaje en función de mi propio criterio. Este criterio lo querremos maximizar. Para obtener estos valores he mantenido las diferencias dadas en la tabla AHP, pero esta vez de forma porcentual.</li>
<li>Eventos deportivos: una media de cuántos torneos por mes. Lo ideal es tener el máximo número de torneos al mes.</li>
<li>Pistas de tenis: nº de pistas de tenis. Es algo objetivo. Cuantas más pistas de tenis tenga un club, mejor será valorado.</li>
<li>Instalaciones: valoración en porcentaje personal. Viendo las instalaciones que ofrecen cada club en sus páginas webs, les proporciono una nota personal. La valoración será en porcentaje y la querremos maximizar.</li>
<li>Ubicación y accesibilidad: tiempo de trayecto. Como hay clubes que se pueden ir andando y otros que se tiene que ir en coche, voy a poner una penalización al tiempo de ir en coche. Es decir, si es necesario ir en coche, voy a añadirle al tiempo 5 mins más debido al aparcamiento y como penalización en sí de tener que coger un vehículo. El objetivo de este criterio será minimizarlo.</li>
<li>Precio: Cuota mensual (euros). El objetivo es minimizar el gasto mensual.</li>
<li>Entrenamientos: valoración en porcentaje personal. Leyendo las descripciones de los clubes en sus páginas webs y por experiencia personal, voy a decidir una nota de lo que creo que van a ser los entrenamientos. El objetivo va a ser maximizar este criterio, pues lo ideal es que los entrenamientos sean intensos y competitivos.</li>
</ul>
<p>Los de minimizar, los añadimos directamente con el menos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>matrizDec <span class="ot">=</span> <span class="fu">multicriterio.crea.matrizdecision</span>(</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">4</span>,  <span class="dv">1</span>,  <span class="dv">50</span>,  <span class="sc">-</span><span class="dv">5</span>,  <span class="sc">-</span><span class="dv">45</span>, <span class="dv">60</span>,</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>    <span class="dv">75</span>,  <span class="dv">3</span>,  <span class="dv">4</span>,  <span class="dv">60</span>,  <span class="sc">-</span><span class="dv">10</span>, <span class="sc">-</span><span class="dv">55</span>, <span class="dv">75</span>,</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>    <span class="dv">50</span>,  <span class="dv">2</span>,  <span class="dv">16</span>, <span class="dv">90</span>,  <span class="sc">-</span><span class="dv">10</span>, <span class="sc">-</span><span class="dv">60</span>, <span class="dv">85</span>,</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>    <span class="dv">25</span>,  <span class="dv">1</span>,  <span class="dv">6</span>,  <span class="dv">20</span>,  <span class="sc">-</span><span class="dv">20</span>, <span class="sc">-</span><span class="dv">70</span>, <span class="dv">100</span>),</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">numalternativas =</span> <span class="dv">4</span>,</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">numcriterios =</span> <span class="dv">7</span>,</span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">v.nombresalt =</span> <span class="fu">c</span>(<span class="st">"Mirador"</span>,<span class="st">"Bernier"</span>,<span class="st">"Río Grande"</span>,<span class="st">"Tenis Betis"</span>),</span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">v.nombrescri =</span> <span class="fu">c</span>(<span class="st">'Fam.'</span>, <span class="st">'Eventos'</span>, <span class="st">'Nº Pistas'</span>, <span class="st">'Instalaciones'</span>, <span class="st">'Ubicación'</span>, <span class="st">'Precio'</span>,<span class="st">'Entr.'</span>)</span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a>matrizDec</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Fam. Eventos Nº Pistas Instalaciones Ubicación Precio Entr.
Mirador      100       4         1            50        -5    -45    60
Bernier       75       3         4            60       -10    -55    75
Río Grande    50       2        16            90       -10    -60    85
Tenis Betis   25       1         6            20       -20    -70   100</code></pre>
</div>
</div>
<p>Vamos a usar los pesos de los criterios que hemos obtenido con el AHP, para poder compararlos. Además, tiene sentido, pues yo soy la que le doy más importancia a uno o a otro criterio.</p>
<p>Además, voy a usar para el test de discordancia los siguientes valores para las diferencias:</p>
<ul>
<li>Eventos deportivos: si hay una diferencia de 5 eventos, para mí esa diferencia es demasiada y por lo tanto la voy a tener en cuenta.</li>
<li>Pistas: si hay una diferencia de 10 pistas. Se puede comprobar la diferencia de dos clubes con el número de pistas de tenis que poseen.</li>
<li>Ubicación y accesibilidad: si hay una diferencia de 15 minutos de trayecto. El tiempo es fundamental para mí. Una diferencia de más de 15 minutos supone grandes consecuencias para mi día.</li>
<li>Precio: si hay una diferencia mensual de 50 euros. Para mí el precio no era un criterio muy importante pues más o menos los precios son similares. Sin embargo, una diferencia de 50 euros sí es algo excesivo.</li>
</ul>
<p>Resolvemos electre con esta información:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>solElec <span class="ot">=</span> <span class="fu">multicriterio.metodoELECTRE_I</span>(</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  matrizDec,</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">pesos.criterios =</span> crisub,</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">nivel.concordancia.minimo.alpha =</span> <span class="fl">0.7</span>,</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">no.se.compensan =</span> <span class="fu">c</span>(<span class="cn">Inf</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="cn">Inf</span>, <span class="dv">15</span>,<span class="dv">50</span>,<span class="cn">Inf</span>),</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">que.alternativas =</span> <span class="cn">TRUE</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a><span class="co">#solElec</span></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a>qgraph<span class="sc">::</span><span class="fu">qgraph</span>(solElec<span class="sc">$</span>relacion.dominante)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in abbreviate(colnames(input), 3): abreviatura utilizada con caracteres
no ASCII</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo2_Reverte_Pagola_Angela_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>solElec<span class="sc">$</span>nucleo_aprox</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Mirador Río Grande 
         1          3 </code></pre>
</div>
</div>
<p>Viendo este grafo y viendo el núcleo obtenido, vamos a modificar el alpha para que nos quedemos solo con una alternativa. Es decir, ponemos más restrictivo el superar el test de concordancia.Y nos quedamos solo con las alternativas posibles: club Mirador y club Río Grande:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>solElec2 <span class="ot">=</span> <span class="fu">multicriterio.metodoELECTRE_I</span>(</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  matrizDec,</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">pesos.criterios =</span> crisub,</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">nivel.concordancia.minimo.alpha =</span> <span class="fl">0.55</span>,</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">no.se.compensan =</span> <span class="fu">c</span>(<span class="cn">Inf</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="cn">Inf</span>, <span class="dv">15</span>,<span class="dv">50</span>,<span class="cn">Inf</span>),</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">que.alternativas =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)</span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a><span class="co">#solElec2</span></span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a>qgraph<span class="sc">::</span><span class="fu">qgraph</span>(solElec2<span class="sc">$</span>relacion.dominante)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in abbreviate(colnames(input), 3): abreviatura utilizada con caracteres
no ASCII</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo2_Reverte_Pagola_Angela_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>solElec2<span class="sc">$</span>nucleo_aprox</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Mirador Río Grande 
         1          2 </code></pre>
</div>
</div>
<p>Puesto que todavía no hemos llegado a ninguna solución, vamos a modificar también el test de discordancia. Como en realidad no necesito tantas pistas de tenis y, además, siempre tengo la opción de alquilarla en cualquier otro lugar, voy a modificar esa restricción.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>solElec3 <span class="ot">=</span> <span class="fu">multicriterio.metodoELECTRE_I</span>(</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  matrizDec,</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">pesos.criterios =</span> crisub,</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">nivel.concordancia.minimo.alpha =</span> <span class="fl">0.55</span>,</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">no.se.compensan =</span> <span class="fu">c</span>(<span class="cn">Inf</span>, <span class="dv">5</span>, <span class="cn">Inf</span>, <span class="cn">Inf</span>, <span class="dv">15</span>,<span class="dv">50</span>,<span class="cn">Inf</span>),</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">que.alternativas =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)</span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a><span class="co">#solElec3</span></span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a>qgraph<span class="sc">::</span><span class="fu">qgraph</span>(solElec3<span class="sc">$</span>relacion.dominante)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in abbreviate(colnames(input), 3): abreviatura utilizada con caracteres
no ASCII</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo2_Reverte_Pagola_Angela_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>solElec3<span class="sc">$</span>nucleo_aprox</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mirador 
      1 </code></pre>
</div>
</div>
<p>CONCLUSIÓN:</p>
<p>Según el procedimiento de Electre también llegamos a la misma conclusión: quedarnos con la alternativa del club Mirador. Con los datos que le he proporcionado, ha sido complicada la elección entre las alternativas de club Mirador y de club Río Grande. Sin embargo, cambiando un poco las restricciones de los test de concordancia y discordancia en función de nuestro criterio y lógica, hemos podido concluir y tomar una decisión.</p>
<div style="page-break-after: always;"></div>
<section id="electre-completo-con-tablas." class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="electre-completo-con-tablas."><span class="header-section-number">2.3.1</span> Electre completo con tablas.</h3>
<p>Por otro lado, si queremos ver los pasos intermedios y las tablas de concordancia y discordancia, lo detallo a continuación. (Detallo solo con las restricciones finales)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Electre con todos los pasos:</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>completo <span class="ot">=</span> <span class="fu">func_ELECTRE_Completo</span>(solElec3)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co">#aquí las tablas de los índices:</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>completo<span class="sc">$</span>MIndices<span class="sc">$</span>KE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">Alts</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">Inds</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">A1</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">A2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="3" style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: blue !important; background-color: white !important; vertical-align: middle !important;">A1</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">I+</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;"></td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">1,2,5,6</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">I=</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">1,2,3,4,5,6,7</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">I-</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;"></td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;">3,4,7</td>
</tr>
<tr class="even">
<td rowspan="3" style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: blue !important; background-color: white !important; vertical-align: middle !important;">A2</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">I+</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">3,4,7</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">I=</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;"></td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">1,2,3,4,5,6,7</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">I-</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;">1,2,5,6</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;"></td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> ELECTRE: Conjunto de Índices</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>


</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co">#tabla del test de concordancia:</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>completo<span class="sc">$</span>TConcordancia<span class="sc">$</span>KE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">Alts</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">Inds</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">A1</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">A2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="3" style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: blue !important; background-color: white !important; vertical-align: middle !important;">A1</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">Ijk</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">1</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">0.713</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">IGjk</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">NaN</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">2.4843</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">TC</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;"><span style="     color: black !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: white !important;">F</span></td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;"><span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: blue !important;">T</span></td>
</tr>
<tr class="even">
<td rowspan="3" style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: blue !important; background-color: white !important; vertical-align: middle !important;">A2</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">Ijk</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">0.287</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">IGjk</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">0.4025</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">NaN</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">TC</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;"><span style="     color: black !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: white !important;">F</span></td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;"><span style="     color: black !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: white !important;">F</span></td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> ELECTRE: Test Concordancia</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>


</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co">#tabla de discordancia:</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>completo<span class="sc">$</span>TDiscordancia<span class="sc">$</span>KE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">Alts</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">Inds</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">A1</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">A2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="3" style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: blue !important; background-color: white !important; vertical-align: middle !important;">A1</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">I-</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;"></td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">3,4,7</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">Djk</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;"></td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">15(Inf),40(Inf),25(Inf)</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">TD</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;">&lt;span style=" color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: blue !important;" &gt;T&lt;/span&gt;</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;">&lt;span style=" color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: blue !important;" &gt;T&lt;/span&gt;</td>
</tr>
<tr class="even">
<td rowspan="3" style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: blue !important; background-color: white !important; vertical-align: middle !important;">A2</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">I-</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">1,2,5,6</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">Djk</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">50(Inf),2(5),5(15),15(50)</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;"></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">TD</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;">&lt;span style=" color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: blue !important;" &gt;T&lt;/span&gt;</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;">&lt;span style=" color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: blue !important;" &gt;T&lt;/span&gt;</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> ELECTRE: Test Discordancia: vd=(Inf,5,Inf,Inf,15,50,Inf)</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>


</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co">#tabla de superación de los dos test:</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>completo<span class="sc">$</span>TSuperacion<span class="sc">$</span>KE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">Alts</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">Inds</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">A1</th>
<th data-quarto-table-cell-role="th" style="text-align: left; color: blue !important;">A2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="3" style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: blue !important; background-color: white !important; vertical-align: middle !important;">A1</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">TC</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">&lt;span style=" color: black !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: white !important;" &gt;F&lt;/span&gt;</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">&lt;span style=" color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;T&lt;/span&gt;</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">TD</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">&lt;span style=" color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;T&lt;/span&gt;</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">&lt;span style=" color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;T&lt;/span&gt;</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">RSup</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;">&lt;span style=" color: black !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: white !important;" &gt;F&lt;/span&gt;</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;">&lt;span style=" color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: blue !important;" &gt;T&lt;/span&gt;</td>
</tr>
<tr class="even">
<td rowspan="3" style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: blue !important; background-color: white !important; vertical-align: middle !important;">A2</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">TC</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">&lt;span style=" color: black !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: white !important;" &gt;F&lt;/span&gt;</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(128, 128, 128, 51) !important; width: 10em;">&lt;span style=" color: black !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: white !important;" &gt;F&lt;/span&gt;</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">TD</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">&lt;span style=" color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;T&lt;/span&gt;</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(179, 179, 179, 51) !important; width: 10em;">&lt;span style=" color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;T&lt;/span&gt;</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 4em; font-weight: bold; color: red !important; border-right: 1px solid;">RSup</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;">&lt;span style=" color: black !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: white !important;" &gt;F&lt;/span&gt;</td>
<td style="text-align: left; font-weight: bold; background-color: rgba(230, 230, 230, 51) !important; width: 10em;">&lt;span style=" color: black !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: white !important;" &gt;F&lt;/span&gt;</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> ELECTRE: Relación Superación: alpha = 0.55, vd=(Inf,5,Inf,Inf,15,50,Inf)</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
<p>Con estas tablas podemos comprobar que el par (a1,a3) supera ambos tests (el de concordancia y el de discordancia), pero que el par (a3,a1) no supera el test de concordancia. Por ello, la alternativa 1 (club Mirador) supera a la alternativa 3 (club Río Grande)</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="resolución-con-promethee-con-r." class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="resolución-con-promethee-con-r."><span class="header-section-number">2.4</span> Resolución con Promethee con R.</h2>
<section id="promethee-i" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="promethee-i"><span class="header-section-number">2.4.1</span> Promethee I</h3>
<p>A continuación voy a resolver el problema con la técnica de Promethee. Para ello, voy usar la misma matriz de decisión, los mismos pesos (para poder comparar y porque realmente muestran mis preferencias). Para las funciones de preferencia, voy a tomar una distinta en cada criterio.</p>
<ul>
<li>Familiaridad: preferencia lineal (q=5,p=30)</li>
<li>Eventos deportivos: cuasi criterio (q=0.5)</li>
<li>Nº Pistas: criterio con preferencia lineal y área de indiferencia (q=2,p=8)</li>
<li>Instalaciones: criterio nivel (q=5,p=30)</li>
<li>Ubicación: criterio usual (p=8)</li>
<li>Precio: preferencia lineal (q=3,p=12)</li>
<li>Entrenamientos: cuasi criterio (q=1)</li>
</ul>
<p>Las funciones de preferencias quedarían así:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co">#                  num fun  q    p   s</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>tab.fpref <span class="ot">=</span> <span class="fu">matrix</span>( <span class="fu">c</span>(<span class="dv">3</span>,    <span class="dv">5</span>,  <span class="dv">30</span>,  <span class="dv">0</span>,</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">2</span>,  <span class="fl">0.5</span>,   <span class="dv">0</span>,  <span class="dv">0</span>,</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">5</span>,    <span class="dv">2</span>,   <span class="dv">8</span>,  <span class="dv">0</span>,</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">4</span>,    <span class="dv">5</span>,  <span class="dv">30</span>,  <span class="dv">0</span>,</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">1</span>,    <span class="dv">0</span>,   <span class="dv">8</span>,  <span class="dv">0</span>,</span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">3</span>,    <span class="dv">3</span>,  <span class="dv">12</span>,  <span class="dv">0</span>,</span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">2</span>,    <span class="dv">1</span>,   <span class="dv">0</span>,  <span class="dv">0</span>),<span class="at">ncol=</span><span class="dv">4</span>,<span class="at">byrow=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Aplico Promethee I en primer lugar:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>tab.Pthee.i <span class="ot">=</span> <span class="fu">multicriterio.metodo.promethee_i</span>(matrizDec,crisub,tab.fpref)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>tab.Pthee.i</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$tabla.indices
              Mirador   Bernier Río Grande Tenis Betis
Mirador     0.0000000 0.6776375  0.7130000   0.7278187
Bernier     0.2055229 0.0000000  0.2444791   0.7278187
Río Grande  0.2870000 0.2870000  0.0000000   0.7813375
Tenis Betis 0.2277406 0.1833000  0.1833000   0.0000000

$vflujos.ent
    Mirador     Bernier  Río Grande Tenis Betis 
  2.1184562   1.1778208   1.3553375   0.5943406 

$vflujos.sal
    Mirador     Bernier  Río Grande Tenis Betis 
  0.7202635   1.1479375   1.1407791   2.2369749 

$tablarelacionsupera
            Mirador Bernier Río Grande Tenis Betis
Mirador         0.5     1.0        1.0         1.0
Bernier         0.0     0.5        0.0         1.0
Río Grande      0.0     1.0        0.5         1.0
Tenis Betis     0.0     0.0        0.0         0.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(qgraph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: qgraph</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qgraph</span>(tab.Pthee.i<span class="sc">$</span>tablarelacionsupera)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in abbreviate(colnames(input), 3): abreviatura utilizada con caracteres
no ASCII</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo2_Reverte_Pagola_Angela_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Según los resultados del Promethee I, Mirador aparece como la alternativa con mayor capacidad de dominancia (mayor flujo entrante), seguida de Río Grande y Bernier, mientras que Tenis Betis resulta la menos preferida al presentar el menor flujo de entrada. En cuanto al flujo saliente (cuánto las alternativas son dominadas por las demás), la menor es club Mirador, seguido de Río Grande, Bernier y, por último, Tenis Betis. La matriz de relación de superación confirma que el club Mirador domina al resto de clubes, evidenciando una clara ventaja respecto a los criterios considerados.</p>
<p>Casualmente ninguna es incomparable ni indiferente, pues los flujos entrantes y salientes están ordenados de la misma manera. Es decir, no existe ninguna alternativa que tenga mejor flujo entrante que otra, pero peor flujo saliente. Por lo que las conclusiones son mucho mejores. Las alernativas con Promethee I quedan ya perfectamente ordenadas.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="promethee-ii" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="promethee-ii"><span class="header-section-number">2.4.2</span> Promethee II</h3>
<p>Para terminar de confirmar nuestras hipótesis, vamos a realizar Promethee II y obtener el ranking final según los flujos netos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>tab.Pthee.ii <span class="ot">=</span> <span class="fu">multicriterio.metodo.promethee_ii</span>(matrizDec,crisub,tab.fpref)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(qgraph)</span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qgraph</span>(tab.Pthee.ii<span class="sc">$</span>tablarelacionsupera)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in abbreviate(colnames(input), 3): abreviatura utilizada con caracteres
no ASCII</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo2_Reverte_Pagola_Angela_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ordenacion final promethee 2:</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>tab.Pthee.ii<span class="sc">$</span>vflujos.netos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Mirador     Bernier  Río Grande Tenis Betis 
 1.39819266  0.02988331  0.21455833 -1.64263430 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">order</span>(tab.Pthee.ii<span class="sc">$</span>vflujos.netos,<span class="at">decreasing=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 3 2 4</code></pre>
</div>
</div>
<p>CONCLUSIONES PROMETHEE:</p>
<p>Como habíamos visto antes, la mejor alternativa según Promethee es el club Mirador, seguida por Río Grande, Bernier y, por último, Tenis Betis.</p>
<p>Además, se puede comprobar la gran diferencia entre los distintos flujos netos, por lo que Promethee realiza una buena diferencia entre las distintas alternativas. También, cabe destacar que la única alternativa con flujo neto negativo es Tenis Betis, por lo que se puede decir que, en general, esta alternativa es más dominada de lo que ella domina.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="promethee-windows." class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="promethee-windows."><span class="header-section-number">2.5</span> Promethee Windows.</h2>
<p>Veamos en primer lugar el planteamiento del problema con Windows. Voy a usar la opción de poner los valores de los criterios de minimizar en positivo, pero especificando si quiero minimizar o maximizar los criterios.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">res =</span> <span class="fu">multicriterio.metodo.promethee_windows</span>(matrizDec,tab.fpref,crisub,</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">fminmax =</span> <span class="fu">c</span>(<span class="st">"max"</span>,<span class="st">"max"</span>,<span class="st">"max"</span>,<span class="st">"max"</span>,<span class="st">"min"</span>,<span class="st">"min"</span>,<span class="st">"max"</span>) ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Escenario
                       Criterio1     Criterio2     Criterio3    Criterio4   
Min/Max                "max"         "max"         "max"        "max"       
Pesos                  "0.17027518"  "0.08512482"  "0.08888127" "0.01481873"
Funciones Preferencias "V-shape (3)" "U-shape (2)" "Linear (5)" "Level (4)" 
Q: Indiferencia        "5"           "0.5"         "2"          "5"         
P: Preferencia         "30"          "0"           "8"          "30"        
S: Gausiano            "0"           "0"           "0"          "0"         
Minimo                 "25"          "1"           "1"          "20"        
Maximo                 "100"         "4"           "16"         "90"        
Media                  "62.5"        "2.5"         "6.75"       "55"        
Desviacion Tipica      "27.95"       "1.12"        "5.63"       "25"        
Mirador                "100"         "4"           "1"          "50"        
Bernier                "75"          "3"           "4"          "60"        
Río Grande             "50"          "2"           "16"         "90"        
Tenis Betis            "25"          "1"           "6"          "20"        
                       Criterio5   Criterio6     Criterio7    
Min/Max                "min"       "min"         "max"        
Pesos                  "0.4157"    "0.0419"      "0.1833"     
Funciones Preferencias "Usual (1)" "V-shape (3)" "U-shape (2)"
Q: Indiferencia        "0"         "3"           "1"          
P: Preferencia         "8"         "12"          "0"          
S: Gausiano            "0"         "0"           "0"          
Minimo                 "5"         "45"          "60"         
Maximo                 "20"        "70"          "100"        
Media                  "11.25"     "57.5"        "80"         
Desviacion Tipica      "5.45"      "9.01"        "14.58"      
Mirador                "5"         "45"          "60"         
Bernier                "10"        "55"          "75"         
Río Grande             "10"        "60"          "85"         
Tenis Betis            "20"        "70"          "100"        

$Acciones
            Rango     Phi Phi.mas Phi.menos
Mirador         1  0.4661  0.7062    0.2401
Río Grande      2  0.0715  0.4518    0.3803
Bernier         3  0.0100  0.3926    0.3826
Tenis Betis     4 -0.5475  0.1981    0.7457</code></pre>
</div>
</div>
<p>Veamos los resultados:</p>
<p>Aunque los flujos netos sean un poco distintos, se sigue manteniendo el mismo orden de preferencias de las alternativas. En primer lugar el club Mirador, con un flujo neto de 0.466, seguido de Río Grande (0.0715), Bernier (0.0100) y, por último, Tenis Betis (-0.5475). Siendo esta última, la única con flujo neto negativo otra vez. Además, vuelven a ser todas comparables y se puede volver a ver un orden de alternativas claro.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="método-axiomático-de-arrow-y-raymond" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="método-axiomático-de-arrow-y-raymond"><span class="header-section-number">2.6</span> Método Axiomático de Arrow y Raymond</h2>
<p>Por último, vamos a usar el método de Arrow y Raymond. Para este método, volvemos a usar la misma matriz de decisión:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>arrow <span class="ot">=</span> <span class="fu">multicriterio.metodoaxiomatico.ArrowRaymond</span>(matrizDec)</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>arrow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$pasos
$pasos[[1]]
$pasos[[1]]$Mclasificacion
            Mirador Bernier Río Grande Tenis Betis
Mirador          NA     4.0        4.0           5
Bernier           3      NA        3.5           5
Río Grande        3     3.5         NA           6
Tenis Betis       2     2.0        1.0          NA

$pasos[[1]]$max.filas
    Mirador     Bernier  Río Grande Tenis Betis 
          5           5           6           2 

$pasos[[1]]$indices.ordenados
[1] 4 1 2 3

$pasos[[1]]$alternativa.sale
[1] "Tenis Betis"


$pasos[[2]]
$pasos[[2]]$Mclasificacion
           Mirador Bernier Río Grande
Mirador         NA     4.0        4.0
Bernier          3      NA        3.5
Río Grande       3     3.5         NA

$pasos[[2]]$max.filas
   Mirador    Bernier Río Grande 
       4.0        3.5        3.5 

$pasos[[2]]$indices.ordenados
[1] 2 3 1

$pasos[[2]]$alternativa.sale
[1] "Bernier"


$pasos[[3]]
$pasos[[3]]$Mclasificacion
           Mirador Río Grande
Mirador         NA          4
Río Grande       3         NA

$pasos[[3]]$max.filas
   Mirador Río Grande 
         4          3 

$pasos[[3]]$indices.ordenados
[1] 2 1

$pasos[[3]]$alternativa.sale
[1] "Río Grande"



$alternativasordenadas
[1] "Mirador"     "Río Grande"  "Bernier"     "Tenis Betis"</code></pre>
</div>
</div>
<p>CONCLUSIONES</p>
<p>Según el método de Arrow y Raymond, la mejor alternativa es el club Mirador, seguido del club Río Grande, Bernier y Tenis Betis.</p>
<p>Además, podemos hacer el análisis de sensibilidad:</p>
<div style="page-break-after: always;"></div>
<section id="análisis-paramétrico-o-de-sensibilidad-aplicación-método-axiomático-de-arrow-y-raymond" class="level3" data-number="2.6.1">
<h3 data-number="2.6.1" class="anchored" data-anchor-id="análisis-paramétrico-o-de-sensibilidad-aplicación-método-axiomático-de-arrow-y-raymond"><span class="header-section-number">2.6.1</span> Análisis paramétrico o de sensibilidad aplicación Método axiomático de Arrow y Raymond</h3>
<p>Vamos a ver cómo cambian los resultados finales si voy modificando las valoraciones de la primera alternativa en todos los criterios (haremos un bucle).</p>
<p>Comenzamos inicialmente con la matriz de decisión usada durante todo el estudio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>intalpha <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="fl">0.1</span>)</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>sols <span class="ot">=</span> <span class="fu">vector</span>(<span class="st">"list"</span>,<span class="fu">length</span>(intalpha))</span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(intalpha)) {</span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>  pej7_i <span class="ot">=</span> matrizDec   <span class="co">#vuelvo a copiar la matriz original</span></span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>  pej7_i[<span class="dv">1</span>,] <span class="ot">=</span> pej7_i[<span class="dv">1</span>,] <span class="sc">*</span> intalpha[i]    <span class="co">#modifico la fila 1</span></span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>  sej7_i <span class="ot">=</span> <span class="fu">multicriterio.metodoaxiomatico.ArrowRaymond</span>(pej7_i)  </span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a>  sols[[i]] <span class="ot">=</span> sej7_i<span class="sc">$</span>alternativasordenadas    <span class="co">#veo el resultado de cada matriz</span></span>
<span id="cb113-8"><a href="#cb113-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb113-9"><a href="#cb113-9" aria-hidden="true" tabindex="-1"></a>sols</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] "Mirador"     "Río Grande"  "Bernier"     "Tenis Betis"

[[2]]
[1] "Mirador"     "Río Grande"  "Bernier"     "Tenis Betis"

[[3]]
[1] "Mirador"     "Río Grande"  "Bernier"     "Tenis Betis"

[[4]]
[1] "Mirador"     "Río Grande"  "Bernier"     "Tenis Betis"

[[5]]
[1] "Río Grande"  "Mirador"     "Bernier"     "Tenis Betis"

[[6]]
[1] "Mirador"     "Río Grande"  "Bernier"     "Tenis Betis"

[[7]]
[1] "Mirador"     "Río Grande"  "Bernier"     "Tenis Betis"

[[8]]
[1] "Mirador"     "Río Grande"  "Bernier"     "Tenis Betis"

[[9]]
[1] "Mirador"     "Río Grande"  "Bernier"     "Tenis Betis"

[[10]]
[1] "Mirador"     "Río Grande"  "Bernier"     "Tenis Betis"

[[11]]
[1] "Mirador"     "Río Grande"  "Bernier"     "Tenis Betis"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co">#veamos las posiciones de a1 en este bucle:</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>posiciones_a1 <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>,<span class="fu">length</span>(intalpha))</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(intalpha)) {</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#i = 1</span></span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>  posiciones_a1[i] <span class="ot">=</span> <span class="fu">which</span>(sols[[i]]<span class="sc">==</span><span class="st">"Mirador"</span>)</span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a>posiciones_a1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1 1 1 1 2 1 1 1 1 1 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ha ido mejorando las posiciones: de 5 a 3</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb117-4"><a href="#cb117-4" aria-hidden="true" tabindex="-1"></a><span class="co">#lo representamos con un plot:</span></span>
<span id="cb117-5"><a href="#cb117-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(intalpha,posiciones_a1,<span class="at">type=</span> <span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo2_Reverte_Pagola_Angela_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>CONCLUSIONES:</p>
<p>Vemos que para todos los valores por los que se multiplica la fila 1 (alternativa Mirador), la alternativa Mirador es la mejor, seguida de: Río Grande, Bernier y Tenis Betis. Sin embargo, hay una excepción, cuando la multiplico por 1,4. En esa iteración, club Mirador y club Río Grande cambian los papeles. Es algo curioso.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="conclusión." class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> CONCLUSIÓN.</h1>
<p>Vemos que en todos los métodos, la alternativa club Mirador es la mejor opción. Tiene sentido pues, con los pesos que se han obtenido con la tabla AHP, la ubicación y accesibilidad es el criterio con más peso, seguido de entrenamientos y familiaridad.</p>
<p>El club Mirador es el mejor ubicado con respecto a mi casa y tiene un gran ambiente al ser un club pequeño y familiar.</p>
<p>En segundo lugar, siempre aparece el club Río Grande, con excepción del método AHP (tercera posición), pero igualado prácticamente con el club Bernier. Por último, el club Tenis Betis siempre es el peor valorado. Tiene sentido, su principal característica son los entrenamientos, pero en todo lo demás siempre toma peores valores que las otras alternativas.</p>
<p>Por lo tanto, tomaría la decisión de apuntarme al club Mirador.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="bibliografía." class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> BIBLIOGRAFÍA.</h1>
<p>Toda la información ha sido extraída de estas páginas webs y de mi experiencia personal (decisión personal que tuve que tomar).</p>
<ul>
<li>https://clubelmirador.com/inicio</li>
<li>https://escueladetenisfermingomez.es/</li>
<li>https://clubbernier.com/</li>
<li>https://riogrande.es/</li>
<li>https://www.tenisbetis.com/index.php?id=10</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>